# GLOBAL

RANDOM_SEED: 1337

# MODEL HYPERPARAMETERS

BATCH_SiZE: 64
LEARNING_RATE: 0.003
TRAIN_SPLIT: 0.9

CONTEXT_SiZE: 16
N_EMBED: 32
N_HEAD: 4
N_LAYER: 4
DROPOUT: 0.2

MAX_ITERS: 100
EVAL_INTERVAL: 10
EVAL_ITERS: 10

TRY_GPU: true

# TRAIN DATA

DATA_FILE_NAME: "messages.txt"