# GLOBAL

RANDOM_SEED: 1337

# MODEL HYPERPARAMETERS

BATCH_SiZE: 64
LEARNING_RATE: 0.003
TRAIN_SPLIT: 0.9

CONTEXT_SiZE: 256
N_EMBED: 384
N_HEAD: 6
N_LAYER: 6
DROPOUT: 0.2

MAX_ITERS: 5000
EVAL_INTERVAL: 500
EVAL_ITERS: 200

TRY_GPU: true

# TRAIN DATA

DATA_FILE_NAME: "messages.txt"